---
title: "World Happiness Report in 2017"
output: html_document
---



## Including Plots

```{r}
data <- readr::read_csv(file = "data/2017.csv")
data$Happiness.Score <- as.integer(data$Happiness.Score)

```

## Plot 1: Happiness Score and GDP per Capital: dont touch here
```{r}
library (ggplot2)
g <- ggplot(data = data, 
mapping = aes(x = Economy..GDP.per.Capita. , y = Happiness.Score, color = Health..Life.Expectancy.)
)
g <- g + geom_smooth()
g <- g + geom_point()
g
```

## Ranking
```{r}
library(plotly)
p <- ggplot(data = data, aes(x = Happiness.Score, y = reorder(Country, Happiness.Score))) + geom_point(colour = "red", alpha = .5) + geom_segment(aes(yend=reorder(Country, Happiness.Score)), xend = 0, colour="pink", alpha = .5) + theme(axis.text.y = element_text(angle = 0, hjust = 1)) + 
labs(title = "World Happiness Rank in 2017", y = "Country", x = "Happiness.Score")
ggplotly(p)

```
```{r}
data <- readr::read_csv(file = "data/2017.csv")
data = data
p <- ggplot(data = data, mapping = aes(x = Trust..Government.Corruption., y = Freedom ))
g <- geom_histogram()
g <- geom_point()

```
